# Generated by Django 2.0.7 on 2018-07-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0002_auto_20180718_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='Add some description', max_length=1000)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='Add some description', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='catalogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_showroom.Catalogue'),
            preserve_default=False,
        ),
    ]
