# Generated by Django 2.0.7 on 2018-07-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0004_auto_20180718_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_showroom.Section'),
            preserve_default=False,
        ),
    ]
