# Generated by Django 2.0.7 on 2018-07-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0007_auto_20180718_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepartlist',
            name='vehiclepart',
        ),
        migrations.RemoveField(
            model_name='section',
            name='vehiclepartlist',
        ),
        migrations.AddField(
            model_name='section',
            name='vehiclepart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_showroom.VehiclePart'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VehiclePartList',
        ),
    ]
