# Generated by Django 2.0.7 on 2018-07-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0008_auto_20180718_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='vehiclepart',
        ),
        migrations.RemoveField(
            model_name='vehiclepart',
            name='catalogue',
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='section',
            field=models.ForeignKey(default=1321, on_delete=django.db.models.deletion.CASCADE, to='car_showroom.Section'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Catalogue',
        ),
    ]
