# Generated by Django 2.0.7 on 2018-07-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0009_auto_20180718_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepart',
            name='section',
        ),
    ]
