# Generated by Django 2.0.7 on 2018-07-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0010_remove_vehiclepart_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepart',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car_showroom.Section'),
            preserve_default=False,
        ),
    ]
